name: ermine_soundscapes
description: Ermine Soundscapes â€“ Flutter Web App with Admin
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  audioplayers: ^6.0.0
  collection: ^1.18.0
  file_picker: ^8.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fitna_icon_location_map_a1.png
    - assets/fitna_icon_start_map_a1.png
    - assets/fitna_icon_end_map_a1.png
    - assets/molen.jpg
    - assets/erminelogo.png
    - assets/favicon-96x96.png
